# =============================================================================
# Google Cloud Build configuration for Cloud Run deployment
# =============================================================================
#
# This file defines the CI/CD pipeline for deploying to Cloud Run.
#
# Prerequisites:
#   1. Enable Cloud Build API: gcloud services enable cloudbuild.googleapis.com
#   2. Enable Cloud Run API: gcloud services enable run.googleapis.com
#   3. Enable Artifact Registry API: gcloud services enable artifactregistry.googleapis.com
#   4. Create Artifact Registry repository:
#      gcloud artifacts repositories create genmedia --repository-format=docker --location=us-central1
#   5. Grant Cloud Build permission to deploy to Cloud Run:
#      gcloud projects add-iam-policy-binding PROJECT_ID \
#        --member="serviceAccount:PROJECT_NUMBER@cloudbuild.gserviceaccount.com" \
#        --role="roles/run.admin"
#      gcloud iam service-accounts add-iam-policy-binding \
#        PROJECT_NUMBER-compute@developer.gserviceaccount.com \
#        --member="serviceAccount:PROJECT_NUMBER@cloudbuild.gserviceaccount.com" \
#        --role="roles/iam.serviceAccountUser"
#
# Trigger options:
#   - Manual: gcloud builds submit --config cloudbuild.yaml
#   - GitHub trigger: Connect repo in Cloud Build console
#
# =============================================================================

substitutions:
  _REGION: us-central1
  _SERVICE_NAME: genmedia-frontend  # Override with genmedia-frontend-dev for dev deployments
  _REPOSITORY: genmedia
  _IMAGE_TAG: latest
  _REQUIRE_AUTH: 'true'
  _VITE_FIREBASE_API_KEY: ''
  _VITE_FIREBASE_AUTH_DOMAIN: ''
  _VITE_FIREBASE_PROJECT_ID: ''
  _VITE_FIREBASE_STORAGE_BUCKET: ''
  _VITE_FIREBASE_MESSAGING_SENDER_ID: ''
  _VITE_FIREBASE_APP_ID: ''
  _VITE_FIREBASE_MEASUREMENT_ID: ''
  _VITE_ALLOWED_EMAILS: ''
  _ALLOWED_ORIGINS: ''
  _FIRESTORE_ENVIRONMENT: 'prod'  # Override with 'dev' for dev deployments
  _RATE_LIMIT_MAX: '200'  # Override with higher value for dev

steps:
  # Step 0: Prepare env vars (unescape ;; back to commas)
  - name: 'bash'
    id: 'prepare-env'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        EMAILS=$$(echo "${_VITE_ALLOWED_EMAILS}" | sed 's/;;/,/g')
        echo "$$EMAILS" > /workspace/allowed_emails.txt
        echo "Allowed emails: $$EMAILS"
        ORIGINS=$$(echo "${_ALLOWED_ORIGINS}" | sed 's/;;/,/g')
        echo "$$ORIGINS" > /workspace/allowed_origins.txt
        echo "Allowed origins: $$ORIGINS"

  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        EMAILS=$$(cat /workspace/allowed_emails.txt)
        docker build \
          -t ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:${_IMAGE_TAG} \
          -t ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:latest \
          --build-arg VITE_FIREBASE_API_KEY=${_VITE_FIREBASE_API_KEY} \
          --build-arg VITE_FIREBASE_AUTH_DOMAIN=${_VITE_FIREBASE_AUTH_DOMAIN} \
          --build-arg VITE_FIREBASE_PROJECT_ID=${_VITE_FIREBASE_PROJECT_ID} \
          --build-arg VITE_FIREBASE_STORAGE_BUCKET=${_VITE_FIREBASE_STORAGE_BUCKET} \
          --build-arg VITE_FIREBASE_MESSAGING_SENDER_ID=${_VITE_FIREBASE_MESSAGING_SENDER_ID} \
          --build-arg VITE_FIREBASE_APP_ID=${_VITE_FIREBASE_APP_ID} \
          --build-arg VITE_FIREBASE_MEASUREMENT_ID=${_VITE_FIREBASE_MEASUREMENT_ID} \
          --build-arg "VITE_ALLOWED_EMAILS=$$EMAILS" \
          .

  # Step 2: Push to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push'
    args:
      - 'push'
      - '--all-tags'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}'

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        ORIGINS=$$(cat /workspace/allowed_origins.txt)
        gcloud run deploy ${_SERVICE_NAME} \
          --image ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:${_IMAGE_TAG} \
          --region ${_REGION} \
          --platform managed \
          --allow-unauthenticated \
          --memory 512Mi \
          --cpu 1 \
          --min-instances 0 \
          --max-instances 10 \
          --set-env-vars "NODE_ENV=production" \
          --set-env-vars "REQUIRE_AUTH=${_REQUIRE_AUTH}" \
          --set-env-vars "GCP_PROJECT_ID=${PROJECT_ID}" \
          --set-env-vars "FIRESTORE_ENVIRONMENT=${_FIRESTORE_ENVIRONMENT}" \
          --set-env-vars "RATE_LIMIT_MAX=${_RATE_LIMIT_MAX}" \
          --set-env-vars "^@^ALLOWED_ORIGINS=$$ORIGINS"

# Store images in Artifact Registry
images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:${_IMAGE_TAG}'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:latest'

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

# Timeout for the entire build (15 minutes)
timeout: '900s'
